version: '3.8'
services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local    
    restart: always
    user: root
    volumes:
      - ./.tmp/dynamodb:/home/dynamodblocal/data
    ports:
      - 8000:8000    
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    working_dir: /home/dynamodblocal
    